blank_issues_enabled: false
contact_links:
  - name: rokartur
    url: https://github.com/rokartur/polish-complete-filters/issues/new
    about: Jeśli potrzebujesz pomocy, skontaktuj się przez nowe issue.
